from utils.dbUtils import Database, RedshiftDatabase
from psycopg2.extras import RealDictCursor
from utils.responseUtils import Response


class PropertyController :
    def __init__(self):
        self.db = Database()
        self.redshift_db = RedshiftDatabase()
    
    @staticmethod
    def get_property_query(fid):
        query = f'''
                Select  
                fid,
                is_on_market,
                total_surface_area,
                total_construction_area,
                year_built,
                special_facilities,
                unit_land_value,
                land_value,
                key_vus,
                predominant_level,
                total_houses,
                locality_size,
                rent_price_spot2,
                rent_price_per_m2_spot2,
                buy_price_spot2,
                buy_price_per_m2_spot2,
                total_area_spot2,
                property_type_spot2,
                rent_price_inmuebles24,
                rent_price_per_m2_inmuebles24,
                buy_price_inmuebles24,
                buy_price_per_m2_inmuebles24,
                total_area_inmuebles24,
                property_type_inmuebles24,
                rent_price_propiedades,
                rent_price_per_m2_propiedades,
                buy_price_propiedades,
                buy_price_per_m2_propiedades,
                total_area_propiedades,
                brands_active_life_front,
                brands_arts_and_entertainment_front,
                brands_attractions_and_activities_front,
                brands_automotive_front,
                brands_eat_and_drink_front,
                brands_education_front,
                brands_financial_service_front,
                brands_health_and_medical_front,
                brands_public_service_and_government_front,
                brands_retail_front,
                brands_active_life_500m,
                brands_arts_and_entertainment_500m,
                brands_attractions_and_activities_500m,
                brands_automotive_500m,
                brands_eat_and_drink_500m,
                brands_education_500m,
                brands_financial_service_500m,
                brands_health_and_medical_500m,
                brands_public_service_and_government_500m,
                brands_retail_500m,
                brands_active_life_1km,
                brands_arts_and_entertainment_1km,
                brands_attractions_and_activities_1km,
                brands_automotive_1km,
                brands_eat_and_drink_1km,
                brands_education_1km,
                brands_financial_service_1km,
                brands_health_and_medical_1km,
                brands_public_service_and_government_1km,
                brands_retail_1km,
                at_rest_avg_x_hour_0_front,
                pedestrian_avg_x_hour_0_front,
                motor_vehicle_avg_x_hour_0_front,
                at_rest_avg_x_hour_1_front,
                pedestrian_avg_x_hour_1_front,
                motor_vehicle_avg_x_hour_1_front,
                at_rest_avg_x_hour_2_front,
                pedestrian_avg_x_hour_2_front,
                motor_vehicle_avg_x_hour_2_front,
                at_rest_avg_x_hour_3_front,
                pedestrian_avg_x_hour_3_front,
                motor_vehicle_avg_x_hour_3_front,
                at_rest_avg_x_hour_4_front,
                pedestrian_avg_x_hour_4_front,
                motor_vehicle_avg_x_hour_4_front,
                at_rest_avg_x_hour_5_front,
                pedestrian_avg_x_hour_5_front,
                motor_vehicle_avg_x_hour_5_front,
                at_rest_avg_x_hour_6_front,
                pedestrian_avg_x_hour_6_front,
                motor_vehicle_avg_x_hour_6_front,
                at_rest_avg_x_hour_7_front,
                pedestrian_avg_x_hour_7_front,
                motor_vehicle_avg_x_hour_7_front,
                at_rest_avg_x_hour_8_front,
                pedestrian_avg_x_hour_8_front,
                motor_vehicle_avg_x_hour_8_front,
                at_rest_avg_x_hour_9_front,
                pedestrian_avg_x_hour_9_front,
                motor_vehicle_avg_x_hour_9_front,
                at_rest_avg_x_hour_10_front,
                pedestrian_avg_x_hour_10_front,
                motor_vehicle_avg_x_hour_10_front,
                at_rest_avg_x_hour_11_front,
                pedestrian_avg_x_hour_11_front,
                motor_vehicle_avg_x_hour_11_front,
                at_rest_avg_x_hour_12_front,
                pedestrian_avg_x_hour_12_front,
                motor_vehicle_avg_x_hour_12_front,
                at_rest_avg_x_hour_13_front,
                pedestrian_avg_x_hour_13_front,
                motor_vehicle_avg_x_hour_13_front,
                at_rest_avg_x_hour_14_front,
                pedestrian_avg_x_hour_14_front,
                motor_vehicle_avg_x_hour_14_front,
                at_rest_avg_x_hour_15_front,
                pedestrian_avg_x_hour_15_front,
                motor_vehicle_avg_x_hour_15_front,
                at_rest_avg_x_hour_16_front,
                pedestrian_avg_x_hour_16_front,
                motor_vehicle_avg_x_hour_16_front,
                at_rest_avg_x_hour_17_front,
                pedestrian_avg_x_hour_17_front,
                motor_vehicle_avg_x_hour_17_front,
                at_rest_avg_x_hour_18_front,
                pedestrian_avg_x_hour_18_front,
                motor_vehicle_avg_x_hour_18_front,
                at_rest_avg_x_hour_19_front,
                pedestrian_avg_x_hour_19_front,
                motor_vehicle_avg_x_hour_19_front,
                at_rest_avg_x_hour_20_front,
                pedestrian_avg_x_hour_20_front,
                motor_vehicle_avg_x_hour_20_front,
                at_rest_avg_x_hour_21_front,
                pedestrian_avg_x_hour_21_front,
                motor_vehicle_avg_x_hour_21_front,
                at_rest_avg_x_hour_22_front,
                pedestrian_avg_x_hour_22_front,
                motor_vehicle_avg_x_hour_22_front,
                at_rest_avg_x_hour_23_front,
                pedestrian_avg_x_hour_23_front,
                motor_vehicle_avg_x_hour_23_front,
                at_rest_avg_x_day_of_week_1_front,
                pedestrian_avg_x_day_of_week_1_front,
                motor_vehicle_avg_x_day_of_week_1_front,
                at_rest_avg_x_day_of_week_2_front,
                pedestrian_avg_x_day_of_week_2_front,
                motor_vehicle_avg_x_day_of_week_2_front,
                at_rest_avg_x_day_of_week_3_front,
                pedestrian_avg_x_day_of_week_3_front,
                motor_vehicle_avg_x_day_of_week_3_front,
                at_rest_avg_x_day_of_week_4_front,
                pedestrian_avg_x_day_of_week_4_front,
                motor_vehicle_avg_x_day_of_week_4_front,
                at_rest_avg_x_day_of_week_5_front,
                pedestrian_avg_x_day_of_week_5_front,
                motor_vehicle_avg_x_day_of_week_5_front,
                at_rest_avg_x_day_of_week_6_front,
                pedestrian_avg_x_day_of_week_6_front,
                motor_vehicle_avg_x_day_of_week_6_front,
                at_rest_avg_x_day_of_week_7_front,
                pedestrian_avg_x_day_of_week_7_front,
                motor_vehicle_avg_x_day_of_week_7_front,
                at_rest_avg_x_day_of_week_1_500m,
                pedestrian_avg_x_day_of_week_1_500m,
                motor_vehicle_avg_x_day_of_week_1_500m,
                at_rest_avg_x_day_of_week_2_500m,
                pedestrian_avg_x_day_of_week_2_500m,
                motor_vehicle_avg_x_day_of_week_2_500m,
                at_rest_avg_x_day_of_week_3_500m,
                pedestrian_avg_x_day_of_week_3_500m,
                motor_vehicle_avg_x_day_of_week_3_500m,
                at_rest_avg_x_day_of_week_4_500m,
                pedestrian_avg_x_day_of_week_4_500m,
                motor_vehicle_avg_x_day_of_week_4_500m,
                at_rest_avg_x_day_of_week_5_500m,
                pedestrian_avg_x_day_of_week_5_500m,
                motor_vehicle_avg_x_day_of_week_5_500m,
                at_rest_avg_x_day_of_week_6_500m,
                pedestrian_avg_x_day_of_week_6_500m,
                motor_vehicle_avg_x_day_of_week_6_500m,
                at_rest_avg_x_day_of_week_7_500m,
                pedestrian_avg_x_day_of_week_7_500m,
                motor_vehicle_avg_x_day_of_week_7_500m,
                at_rest_avg_x_hour_0_500m,
                pedestrian_avg_x_hour_0_500m,
                motor_vehicle_avg_x_hour_0_500m,
                at_rest_avg_x_hour_1_500m,
                pedestrian_avg_x_hour_1_500m,
                motor_vehicle_avg_x_hour_1_500m,
                at_rest_avg_x_hour_2_500m,
                pedestrian_avg_x_hour_2_500m,
                motor_vehicle_avg_x_hour_2_500m,
                at_rest_avg_x_hour_3_500m,
                pedestrian_avg_x_hour_3_500m,
                motor_vehicle_avg_x_hour_3_500m,
                at_rest_avg_x_hour_4_500m,
                pedestrian_avg_x_hour_4_500m,
                motor_vehicle_avg_x_hour_4_500m,
                at_rest_avg_x_hour_5_500m,
                pedestrian_avg_x_hour_5_500m,
                motor_vehicle_avg_x_hour_5_500m,
                at_rest_avg_x_hour_6_500m,
                pedestrian_avg_x_hour_6_500m,
                motor_vehicle_avg_x_hour_6_500m,
                at_rest_avg_x_hour_7_500m,
                pedestrian_avg_x_hour_7_500m,
                motor_vehicle_avg_x_hour_7_500m,
                at_rest_avg_x_hour_8_500m,
                pedestrian_avg_x_hour_8_500m,
                motor_vehicle_avg_x_hour_8_500m,
                at_rest_avg_x_hour_9_500m,
                pedestrian_avg_x_hour_9_500m,
                motor_vehicle_avg_x_hour_9_500m,
                at_rest_avg_x_hour_10_500m,
                pedestrian_avg_x_hour_10_500m,
                motor_vehicle_avg_x_hour_10_500m,
                at_rest_avg_x_hour_11_500m,
                pedestrian_avg_x_hour_11_500m,
                motor_vehicle_avg_x_hour_11_500m,
                at_rest_avg_x_hour_12_500m,
                pedestrian_avg_x_hour_12_500m,
                motor_vehicle_avg_x_hour_12_500m,
                at_rest_avg_x_hour_13_500m,
                pedestrian_avg_x_hour_13_500m,
                motor_vehicle_avg_x_hour_13_500m,
                at_rest_avg_x_hour_14_500m,
                pedestrian_avg_x_hour_14_500m,
                motor_vehicle_avg_x_hour_14_500m,
                at_rest_avg_x_hour_15_500m,
                pedestrian_avg_x_hour_15_500m,
                motor_vehicle_avg_x_hour_15_500m,
                at_rest_avg_x_hour_16_500m,
                pedestrian_avg_x_hour_16_500m,
                motor_vehicle_avg_x_hour_16_500m,
                at_rest_avg_x_hour_17_500m,
                pedestrian_avg_x_hour_17_500m,
                motor_vehicle_avg_x_hour_17_500m,
                at_rest_avg_x_hour_18_500m,
                pedestrian_avg_x_hour_18_500m,
                motor_vehicle_avg_x_hour_18_500m,
                at_rest_avg_x_hour_19_500m,
                pedestrian_avg_x_hour_19_500m,
                motor_vehicle_avg_x_hour_19_500m,
                at_rest_avg_x_hour_20_500m,
                pedestrian_avg_x_hour_20_500m,
                motor_vehicle_avg_x_hour_20_500m,
                at_rest_avg_x_hour_21_500m,
                pedestrian_avg_x_hour_21_500m,
                motor_vehicle_avg_x_hour_21_500m,
                at_rest_avg_x_hour_22_500m,
                pedestrian_avg_x_hour_22_500m,
                motor_vehicle_avg_x_hour_22_500m,
                at_rest_avg_x_hour_23_500m,
                pedestrian_avg_x_hour_23_500m,
                motor_vehicle_avg_x_hour_23_500m
                FROM blackprint_db_prd.data_product.v_parcel_v3 
                where fid = {fid}               
        '''
        return query
    
    @staticmethod
    def get_property_json(result):
        try :
            property_details = {
                "fid": result[0]["fid"],
                "is_on_market": result[0]["is_on_market"],
                "total_surface_area": result[0]["total_surface_area"],
                "total_construction_area": result[0]["total_construction_area"],
                "year_built": result[0]["year_built"],
                "special_facilities": result[0]["special_facilities"],
                "unit_land_value": result[0]["unit_land_value"],
                "land_value": result[0]["land_value"],
                "key_vus": result[0]["key_vus"],
                "predominant_level": result[0]["predominant_level"],
                "total_houses": result[0]["total_houses"],
                "locality_size": result[0]["locality_size"]
            }

            market_info = {
                "rent_price_spot2": result[0]["rent_price_spot2"],
                "rent_price_per_m2_spot2": result[0]["rent_price_per_m2_spot2"],
                "buy_price_spot2": result[0]["buy_price_spot2"],
                "buy_price_per_m2_spot2": result[0]["buy_price_per_m2_spot2"],
                "total_area_spot2": result[0]["total_area_spot2"],
                "property_type_spot2": result[0]["property_type_spot2"],
                "rent_price_inmuebles24": result[0]["rent_price_inmuebles24"],
                "rent_price_per_m2_inmuebles24": result[0]["rent_price_per_m2_inmuebles24"],
                "buy_price_inmuebles24": result[0]["buy_price_inmuebles24"],
                "buy_price_per_m2_inmuebles24": result[0]["buy_price_per_m2_inmuebles24"],
                "total_area_inmuebles24": result[0]["total_area_inmuebles24"],
                "property_type_inmuebles24": result[0]["property_type_inmuebles24"],
                "rent_price_propiedades": result[0]["rent_price_propiedades"],
                "rent_price_per_m2_propiedades": result[0]["rent_price_per_m2_propiedades"],
                "buy_price_propiedades": result[0]["buy_price_propiedades"],
                "buy_price_per_m2_propiedades": result[0]["buy_price_per_m2_propiedades"],
                "total_area_propiedades": result[0]["total_area_propiedades"],
                "property_images" : []
            }

            pois = {
                "brands_active_life_front": result[0]["brands_active_life_front"],
                "brands_arts_and_entertainment_front": result[0]["brands_arts_and_entertainment_front"],
                "brands_attractions_and_activities_front": result[0]["brands_attractions_and_activities_front"],
                "brands_automotive_front": result[0]["brands_automotive_front"],
                "brands_eat_and_drink_front": result[0]["brands_eat_and_drink_front"],
                "brands_education_front": result[0]["brands_education_front"],
                "brands_financial_service_front": result[0]["brands_financial_service_front"],
                "brands_health_and_medical_front": result[0]["brands_health_and_medical_front"],
                "brands_public_service_and_government_front": result[0]["brands_public_service_and_government_front"],
                "brands_retail_front": result[0]["brands_retail_front"],
                "brands_active_life_500m": result[0]["brands_active_life_500m"],
                "brands_arts_and_entertainment_500m": result[0]["brands_arts_and_entertainment_500m"],
                "brands_attractions_and_activities_500m": result[0]["brands_attractions_and_activities_500m"],
                "brands_automotive_500m": result[0]["brands_automotive_500m"],
                "brands_eat_and_drink_500m": result[0]["brands_eat_and_drink_500m"],
                "brands_education_500m": result[0]["brands_education_500m"],
                "brands_financial_service_500m": result[0]["brands_financial_service_500m"],
                "brands_health_and_medical_500m": result[0]["brands_health_and_medical_500m"],
                "brands_public_service_and_government_500m": result[0]["brands_public_service_and_government_500m"],
                "brands_retail_500m": result[0]["brands_retail_500m"],
                "brands_active_life_1km": result[0]["brands_active_life_1km"],
                "brands_arts_and_entertainment_1km": result[0]["brands_arts_and_entertainment_1km"],
                "brands_attractions_and_activities_1km": result[0]["brands_attractions_and_activities_1km"],
                "brands_automotive_1km": result[0]["brands_automotive_1km"],
                "brands_eat_and_drink_1km": result[0]["brands_eat_and_drink_1km"],
                "brands_education_1km": result[0]["brands_education_1km"],
                "brands_financial_service_1km": result[0]["brands_financial_service_1km"],
                "brands_health_and_medical_1km": result[0]["brands_health_and_medical_1km"],
                "brands_public_service_and_government_1km": result[0]["brands_public_service_and_government_1km"],
                "brands_retail_1km": result[0]["brands_retail_1km"]
            }

            traffic = {
                "front" : {
                "at_rest_avg_x_hour_0_front": result[0]["at_rest_avg_x_hour_0_front"],
                "pedestrian_avg_x_hour_0_front": result[0]["pedestrian_avg_x_hour_0_front"],
                "motor_vehicle_avg_x_hour_0_front": result[0]["motor_vehicle_avg_x_hour_0_front"],
                "at_rest_avg_x_hour_1_front": result[0]["at_rest_avg_x_hour_1_front"],
                "pedestrian_avg_x_hour_1_front": result[0]["pedestrian_avg_x_hour_1_front"],
                "motor_vehicle_avg_x_hour_1_front": result[0]["motor_vehicle_avg_x_hour_1_front"],
                "at_rest_avg_x_hour_2_front": result[0]["at_rest_avg_x_hour_2_front"],
                "pedestrian_avg_x_hour_2_front": result[0]["pedestrian_avg_x_hour_2_front"],
                "motor_vehicle_avg_x_hour_2_front": result[0]["motor_vehicle_avg_x_hour_2_front"],
                "at_rest_avg_x_hour_3_front": result[0]["at_rest_avg_x_hour_3_front"],
                "pedestrian_avg_x_hour_3_front": result[0]["pedestrian_avg_x_hour_3_front"],
                "motor_vehicle_avg_x_hour_3_front": result[0]["motor_vehicle_avg_x_hour_3_front"],
                "at_rest_avg_x_hour_4_front": result[0]["at_rest_avg_x_hour_4_front"],
                "pedestrian_avg_x_hour_4_front": result[0]["pedestrian_avg_x_hour_4_front"],
                "motor_vehicle_avg_x_hour_4_front": result[0]["motor_vehicle_avg_x_hour_4_front"],
                "at_rest_avg_x_hour_5_front": result[0]["at_rest_avg_x_hour_5_front"],
                "pedestrian_avg_x_hour_5_front": result[0]["pedestrian_avg_x_hour_5_front"],
                "motor_vehicle_avg_x_hour_5_front": result[0]["motor_vehicle_avg_x_hour_5_front"],
                "at_rest_avg_x_hour_6_front": result[0]["at_rest_avg_x_hour_6_front"],
                "pedestrian_avg_x_hour_6_front": result[0]["pedestrian_avg_x_hour_6_front"],
                "motor_vehicle_avg_x_hour_6_front": result[0]["motor_vehicle_avg_x_hour_6_front"],
                "at_rest_avg_x_hour_7_front": result[0]["at_rest_avg_x_hour_7_front"],
                "pedestrian_avg_x_hour_7_front": result[0]["pedestrian_avg_x_hour_7_front"],
                "motor_vehicle_avg_x_hour_7_front": result[0]["motor_vehicle_avg_x_hour_7_front"],
                "at_rest_avg_x_hour_8_front": result[0]["at_rest_avg_x_hour_8_front"],
                "pedestrian_avg_x_hour_8_front": result[0]["pedestrian_avg_x_hour_8_front"],
                "motor_vehicle_avg_x_hour_8_front": result[0]["motor_vehicle_avg_x_hour_8_front"],
                "at_rest_avg_x_hour_9_front": result[0]["at_rest_avg_x_hour_9_front"],
                "pedestrian_avg_x_hour_9_front": result[0]["pedestrian_avg_x_hour_9_front"],
                "motor_vehicle_avg_x_hour_9_front": result[0]["motor_vehicle_avg_x_hour_9_front"],
                "at_rest_avg_x_hour_10_front": result[0]["at_rest_avg_x_hour_10_front"],
                "pedestrian_avg_x_hour_10_front": result[0]["pedestrian_avg_x_hour_10_front"],
                "motor_vehicle_avg_x_hour_10_front": result[0]["motor_vehicle_avg_x_hour_10_front"],
                "at_rest_avg_x_hour_11_front": result[0]["at_rest_avg_x_hour_11_front"],
                "pedestrian_avg_x_hour_11_front": result[0]["pedestrian_avg_x_hour_11_front"],
                "motor_vehicle_avg_x_hour_11_front": result[0]["motor_vehicle_avg_x_hour_11_front"],
                "at_rest_avg_x_hour_12_front": result[0]["at_rest_avg_x_hour_12_front"],
                "pedestrian_avg_x_hour_12_front": result[0]["pedestrian_avg_x_hour_12_front"],
                "motor_vehicle_avg_x_hour_12_front": result[0]["motor_vehicle_avg_x_hour_12_front"],
                "at_rest_avg_x_hour_13_front": result[0]["at_rest_avg_x_hour_13_front"],
                "pedestrian_avg_x_hour_13_front": result[0]["pedestrian_avg_x_hour_13_front"],
                "motor_vehicle_avg_x_hour_13_front": result[0]["motor_vehicle_avg_x_hour_13_front"],
                "at_rest_avg_x_hour_14_front": result[0]["at_rest_avg_x_hour_14_front"],
                "pedestrian_avg_x_hour_14_front": result[0]["pedestrian_avg_x_hour_14_front"],
                "motor_vehicle_avg_x_hour_14_front": result[0]["motor_vehicle_avg_x_hour_14_front"],
                "at_rest_avg_x_hour_15_front": result[0]["at_rest_avg_x_hour_15_front"],
                "pedestrian_avg_x_hour_15_front": result[0]["pedestrian_avg_x_hour_15_front"],
                "motor_vehicle_avg_x_hour_15_front": result[0]["motor_vehicle_avg_x_hour_15_front"],
                "at_rest_avg_x_hour_16_front": result[0]["at_rest_avg_x_hour_16_front"],
                "pedestrian_avg_x_hour_16_front": result[0]["pedestrian_avg_x_hour_16_front"],
                "motor_vehicle_avg_x_hour_16_front": result[0]["motor_vehicle_avg_x_hour_16_front"],
                "at_rest_avg_x_hour_17_front": result[0]["at_rest_avg_x_hour_17_front"],
                "pedestrian_avg_x_hour_17_front": result[0]["pedestrian_avg_x_hour_17_front"],
                "motor_vehicle_avg_x_hour_17_front": result[0]["motor_vehicle_avg_x_hour_17_front"],
                "at_rest_avg_x_hour_18_front": result[0]["at_rest_avg_x_hour_18_front"],
                "pedestrian_avg_x_hour_18_front": result[0]["pedestrian_avg_x_hour_18_front"],
                "motor_vehicle_avg_x_hour_18_front": result[0]["motor_vehicle_avg_x_hour_18_front"],
                "at_rest_avg_x_hour_19_front": result[0]["at_rest_avg_x_hour_19_front"],
                "pedestrian_avg_x_hour_19_front": result[0]["pedestrian_avg_x_hour_19_front"],
                "motor_vehicle_avg_x_hour_19_front": result[0]["motor_vehicle_avg_x_hour_19_front"],
                "at_rest_avg_x_hour_20_front": result[0]["at_rest_avg_x_hour_20_front"],
                "pedestrian_avg_x_hour_20_front": result[0]["pedestrian_avg_x_hour_20_front"],
                "motor_vehicle_avg_x_hour_20_front": result[0]["motor_vehicle_avg_x_hour_20_front"],
                "at_rest_avg_x_hour_21_front": result[0]["at_rest_avg_x_hour_21_front"],
                "pedestrian_avg_x_hour_21_front": result[0]["pedestrian_avg_x_hour_21_front"],
                "motor_vehicle_avg_x_hour_21_front": result[0]["motor_vehicle_avg_x_hour_21_front"],
                "at_rest_avg_x_hour_22_front": result[0]["at_rest_avg_x_hour_22_front"],
                "pedestrian_avg_x_hour_22_front": result[0]["pedestrian_avg_x_hour_22_front"],
                "motor_vehicle_avg_x_hour_22_front": result[0]["motor_vehicle_avg_x_hour_22_front"],
                "at_rest_avg_x_hour_23_front": result[0]["at_rest_avg_x_hour_23_front"],
                "pedestrian_avg_x_hour_23_front": result[0]["pedestrian_avg_x_hour_23_front"],
                "motor_vehicle_avg_x_hour_23_front": result[0]["motor_vehicle_avg_x_hour_23_front"],
                "at_rest_avg_x_day_of_week_1_front": result[0]["at_rest_avg_x_day_of_week_1_front"],
                "pedestrian_avg_x_day_of_week_1_front": result[0]["pedestrian_avg_x_day_of_week_1_front"],
                "motor_vehicle_avg_x_day_of_week_1_front": result[0]["motor_vehicle_avg_x_day_of_week_1_front"],
                "at_rest_avg_x_day_of_week_2_front": result[0]["at_rest_avg_x_day_of_week_2_front"],
                "pedestrian_avg_x_day_of_week_2_front": result[0]["pedestrian_avg_x_day_of_week_2_front"],
                "motor_vehicle_avg_x_day_of_week_2_front": result[0]["motor_vehicle_avg_x_day_of_week_2_front"],
                "at_rest_avg_x_day_of_week_3_front": result[0]["at_rest_avg_x_day_of_week_3_front"],
                "pedestrian_avg_x_day_of_week_3_front": result[0]["pedestrian_avg_x_day_of_week_3_front"],
                "motor_vehicle_avg_x_day_of_week_3_front": result[0]["motor_vehicle_avg_x_day_of_week_3_front"],
                "at_rest_avg_x_day_of_week_4_front": result[0]["at_rest_avg_x_day_of_week_4_front"],
                "pedestrian_avg_x_day_of_week_4_front": result[0]["pedestrian_avg_x_day_of_week_4_front"],
                "motor_vehicle_avg_x_day_of_week_4_front": result[0]["motor_vehicle_avg_x_day_of_week_4_front"],
                "at_rest_avg_x_day_of_week_5_front": result[0]["at_rest_avg_x_day_of_week_5_front"],
                "pedestrian_avg_x_day_of_week_5_front": result[0]["pedestrian_avg_x_day_of_week_5_front"],
                "motor_vehicle_avg_x_day_of_week_5_front": result[0]["motor_vehicle_avg_x_day_of_week_5_front"],
                "at_rest_avg_x_day_of_week_6_front": result[0]["at_rest_avg_x_day_of_week_6_front"],
                "pedestrian_avg_x_day_of_week_6_front": result[0]["pedestrian_avg_x_day_of_week_6_front"],
                "motor_vehicle_avg_x_day_of_week_6_front": result[0]["motor_vehicle_avg_x_day_of_week_6_front"],
                "at_rest_avg_x_day_of_week_7_front": result[0]["at_rest_avg_x_day_of_week_7_front"],
                "pedestrian_avg_x_day_of_week_7_front": result[0]["pedestrian_avg_x_day_of_week_7_front"],
                "motor_vehicle_avg_x_day_of_week_7_front": result[0]["motor_vehicle_avg_x_day_of_week_7_front"],
                } ,
                "500m" : {
                "at_rest_avg_x_day_of_week_1_500m": result[0]["at_rest_avg_x_day_of_week_1_500m"],
                "pedestrian_avg_x_day_of_week_1_500m": result[0]["pedestrian_avg_x_day_of_week_1_500m"],
                "motor_vehicle_avg_x_day_of_week_1_500m": result[0]["motor_vehicle_avg_x_day_of_week_1_500m"],
                "at_rest_avg_x_day_of_week_2_500m": result[0]["at_rest_avg_x_day_of_week_2_500m"],
                "pedestrian_avg_x_day_of_week_2_500m": result[0]["pedestrian_avg_x_day_of_week_2_500m"],
                "motor_vehicle_avg_x_day_of_week_2_500m": result[0]["motor_vehicle_avg_x_day_of_week_2_500m"],
                "at_rest_avg_x_day_of_week_3_500m": result[0]["at_rest_avg_x_day_of_week_3_500m"],
                "pedestrian_avg_x_day_of_week_3_500m": result[0]["pedestrian_avg_x_day_of_week_3_500m"],
                "motor_vehicle_avg_x_day_of_week_3_500m": result[0]["motor_vehicle_avg_x_day_of_week_3_500m"],
                "at_rest_avg_x_day_of_week_4_500m": result[0]["at_rest_avg_x_day_of_week_4_500m"],
                "pedestrian_avg_x_day_of_week_4_500m": result[0]["pedestrian_avg_x_day_of_week_4_500m"],
                "motor_vehicle_avg_x_day_of_week_4_500m": result[0]["motor_vehicle_avg_x_day_of_week_4_500m"],
                "at_rest_avg_x_day_of_week_5_500m": result[0]["at_rest_avg_x_day_of_week_5_500m"],
                "pedestrian_avg_x_day_of_week_5_500m": result[0]["pedestrian_avg_x_day_of_week_5_500m"],
                "motor_vehicle_avg_x_day_of_week_5_500m": result[0]["motor_vehicle_avg_x_day_of_week_5_500m"],
                "at_rest_avg_x_day_of_week_6_500m": result[0]["at_rest_avg_x_day_of_week_6_500m"],
                "pedestrian_avg_x_day_of_week_6_500m": result[0]["pedestrian_avg_x_day_of_week_6_500m"],
                "motor_vehicle_avg_x_day_of_week_6_500m": result[0]["motor_vehicle_avg_x_day_of_week_6_500m"],
                "at_rest_avg_x_day_of_week_7_500m": result[0]["at_rest_avg_x_day_of_week_7_500m"],
                "pedestrian_avg_x_day_of_week_7_500m": result[0]["pedestrian_avg_x_day_of_week_7_500m"],
                "motor_vehicle_avg_x_day_of_week_7_500m": result[0]["motor_vehicle_avg_x_day_of_week_7_500m"],
                "at_rest_avg_x_hour_0_500m": result[0]["at_rest_avg_x_hour_0_500m"],
                "pedestrian_avg_x_hour_0_500m": result[0]["pedestrian_avg_x_hour_0_500m"],
                "motor_vehicle_avg_x_hour_0_500m": result[0]["motor_vehicle_avg_x_hour_0_500m"],
                "at_rest_avg_x_hour_1_500m": result[0]["at_rest_avg_x_hour_1_500m"],
                "pedestrian_avg_x_hour_1_500m": result[0]["pedestrian_avg_x_hour_1_500m"],
                "motor_vehicle_avg_x_hour_1_500m": result[0]["motor_vehicle_avg_x_hour_1_500m"],
                "at_rest_avg_x_hour_2_500m": result[0]["at_rest_avg_x_hour_2_500m"],
                "pedestrian_avg_x_hour_2_500m": result[0]["pedestrian_avg_x_hour_2_500m"],
                "motor_vehicle_avg_x_hour_2_500m": result[0]["motor_vehicle_avg_x_hour_2_500m"],
                "at_rest_avg_x_hour_3_500m": result[0]["at_rest_avg_x_hour_3_500m"],
                "pedestrian_avg_x_hour_3_500m": result[0]["pedestrian_avg_x_hour_3_500m"],
                "motor_vehicle_avg_x_hour_3_500m": result[0]["motor_vehicle_avg_x_hour_3_500m"],
                "at_rest_avg_x_hour_4_500m": result[0]["at_rest_avg_x_hour_4_500m"],
                "pedestrian_avg_x_hour_4_500m": result[0]["pedestrian_avg_x_hour_4_500m"],
                "motor_vehicle_avg_x_hour_4_500m": result[0]["motor_vehicle_avg_x_hour_4_500m"],
                "at_rest_avg_x_hour_5_500m": result[0]["at_rest_avg_x_hour_5_500m"],
                "pedestrian_avg_x_hour_5_500m": result[0]["pedestrian_avg_x_hour_5_500m"],
                "motor_vehicle_avg_x_hour_5_500m": result[0]["motor_vehicle_avg_x_hour_5_500m"],
                "at_rest_avg_x_hour_6_500m": result[0]["at_rest_avg_x_hour_6_500m"],
                "pedestrian_avg_x_hour_6_500m": result[0]["pedestrian_avg_x_hour_6_500m"],
                "motor_vehicle_avg_x_hour_6_500m": result[0]["motor_vehicle_avg_x_hour_6_500m"],
                "at_rest_avg_x_hour_7_500m": result[0]["at_rest_avg_x_hour_7_500m"],
                "pedestrian_avg_x_hour_7_500m": result[0]["pedestrian_avg_x_hour_7_500m"],
                "motor_vehicle_avg_x_hour_7_500m": result[0]["motor_vehicle_avg_x_hour_7_500m"],
                "at_rest_avg_x_hour_8_500m": result[0]["at_rest_avg_x_hour_8_500m"],
                "pedestrian_avg_x_hour_8_500m": result[0]["pedestrian_avg_x_hour_8_500m"],
                "motor_vehicle_avg_x_hour_8_500m": result[0]["motor_vehicle_avg_x_hour_8_500m"],
                "at_rest_avg_x_hour_9_500m": result[0]["at_rest_avg_x_hour_9_500m"],
                "pedestrian_avg_x_hour_9_500m": result[0]["pedestrian_avg_x_hour_9_500m"],
                "motor_vehicle_avg_x_hour_9_500m": result[0]["motor_vehicle_avg_x_hour_9_500m"],
                "at_rest_avg_x_hour_10_500m": result[0]["at_rest_avg_x_hour_10_500m"],
                "pedestrian_avg_x_hour_10_500m": result[0]["pedestrian_avg_x_hour_10_500m"],
                "motor_vehicle_avg_x_hour_10_500m": result[0]["motor_vehicle_avg_x_hour_10_500m"],
                "at_rest_avg_x_hour_11_500m": result[0]["at_rest_avg_x_hour_11_500m"],
                "pedestrian_avg_x_hour_11_500m": result[0]["pedestrian_avg_x_hour_11_500m"],
                "motor_vehicle_avg_x_hour_11_500m": result[0]["motor_vehicle_avg_x_hour_11_500m"],
                "at_rest_avg_x_hour_12_500m": result[0]["at_rest_avg_x_hour_12_500m"],
                "pedestrian_avg_x_hour_12_500m": result[0]["pedestrian_avg_x_hour_12_500m"],
                "motor_vehicle_avg_x_hour_12_500m": result[0]["motor_vehicle_avg_x_hour_12_500m"],
                "at_rest_avg_x_hour_13_500m": result[0]["at_rest_avg_x_hour_13_500m"],
                "pedestrian_avg_x_hour_13_500m": result[0]["pedestrian_avg_x_hour_13_500m"],
                "motor_vehicle_avg_x_hour_13_500m": result[0]["motor_vehicle_avg_x_hour_13_500m"],
                "at_rest_avg_x_hour_14_500m": result[0]["at_rest_avg_x_hour_14_500m"],
                "pedestrian_avg_x_hour_14_500m": result[0]["pedestrian_avg_x_hour_14_500m"],
                "motor_vehicle_avg_x_hour_14_500m": result[0]["motor_vehicle_avg_x_hour_14_500m"],
                "at_rest_avg_x_hour_15_500m": result[0]["at_rest_avg_x_hour_15_500m"],
                "pedestrian_avg_x_hour_15_500m": result[0]["pedestrian_avg_x_hour_15_500m"],
                "motor_vehicle_avg_x_hour_15_500m": result[0]["motor_vehicle_avg_x_hour_15_500m"],
                "at_rest_avg_x_hour_16_500m": result[0]["at_rest_avg_x_hour_16_500m"],
                "pedestrian_avg_x_hour_16_500m": result[0]["pedestrian_avg_x_hour_16_500m"],
                "motor_vehicle_avg_x_hour_16_500m": result[0]["motor_vehicle_avg_x_hour_16_500m"],
                "at_rest_avg_x_hour_17_500m": result[0]["at_rest_avg_x_hour_17_500m"],
                "pedestrian_avg_x_hour_17_500m": result[0]["pedestrian_avg_x_hour_17_500m"],
                "motor_vehicle_avg_x_hour_17_500m": result[0]["motor_vehicle_avg_x_hour_17_500m"],
                "at_rest_avg_x_hour_18_500m": result[0]["at_rest_avg_x_hour_18_500m"],
                "pedestrian_avg_x_hour_18_500m": result[0]["pedestrian_avg_x_hour_18_500m"],
                "motor_vehicle_avg_x_hour_18_500m": result[0]["motor_vehicle_avg_x_hour_18_500m"],
                "at_rest_avg_x_hour_19_500m": result[0]["at_rest_avg_x_hour_19_500m"],
                "pedestrian_avg_x_hour_19_500m": result[0]["pedestrian_avg_x_hour_19_500m"],
                "motor_vehicle_avg_x_hour_19_500m": result[0]["motor_vehicle_avg_x_hour_19_500m"],
                "at_rest_avg_x_hour_20_500m": result[0]["at_rest_avg_x_hour_20_500m"],
                "pedestrian_avg_x_hour_20_500m": result[0]["pedestrian_avg_x_hour_20_500m"],
                "motor_vehicle_avg_x_hour_20_500m": result[0]["motor_vehicle_avg_x_hour_20_500m"],
                "at_rest_avg_x_hour_21_500m": result[0]["at_rest_avg_x_hour_21_500m"],
                "pedestrian_avg_x_hour_21_500m": result[0]["pedestrian_avg_x_hour_21_500m"],
                "motor_vehicle_avg_x_hour_21_500m": result[0]["motor_vehicle_avg_x_hour_21_500m"],
                "at_rest_avg_x_hour_22_500m": result[0]["at_rest_avg_x_hour_22_500m"],
                "pedestrian_avg_x_hour_22_500m": result[0]["pedestrian_avg_x_hour_22_500m"],
                "motor_vehicle_avg_x_hour_22_500m": result[0]["motor_vehicle_avg_x_hour_22_500m"],
                "at_rest_avg_x_hour_23_500m": result[0]["at_rest_avg_x_hour_23_500m"],
                "pedestrian_avg_x_hour_23_500m": result[0]["pedestrian_avg_x_hour_23_500m"],
                "motor_vehicle_avg_x_hour_23_500m": result[0]["motor_vehicle_avg_x_hour_23_500m"]
                } ,
                "1km" : {}
                }
            demographic = {}

            return property_details, market_info, pois, traffic, demographic

        except Exception as e :
            return Response.internal_server_error(message=str(e))

    def get_properties(self, fid):
        connection = None 
        cursor = None
        try :
            query = self.get_property_query(fid)
            connection = self.redshift_db.connect()
            cursor = connection.cursor(cursor_factory=RealDictCursor)
            cursor.execute(query)
            result = cursor.fetchall()
            property_details,  market_info, pois, traffic, demographic = self.get_property_json(result)
            result_json = {
                "property_details": property_details,
                "market_info": market_info,
                "pois": pois,
                "traffic": traffic,
                "demographic": demographic
            }
            resp = Response.success(data=result_json, message='Success')
        except Exception as e :
            if connection:
                connection.rollback()
            resp =  Response.internal_server_error(message=str(e))
        finally :
            return resp

    def get_property_market_info(self, fid):
        connection = None
        cursor = None
        try :
            connection = self.db.connect()
            cursor = connection.cursor(cursor_factory=RealDictCursor)
            spot2_query = f''' SELECT 
                        id_market_data_spot2 as id_spot2,
                        title as title_spot2,
                        address as address_spot2,
                        delegacion as delegacion_spot2,
                        latitude as latitude_spot2,
                        longitude as longitude_spot2,
                        description as description_spot2,
                        operation_type as operation_type_spot2,
                        rent_price_clean as rent_price_mxn_spot2,
                        rent_price_per_m2 as rent_price_per_m2_spot2,
                        buy_price_clean as buy_price_mxn_spot2,
                        buy_price_per_m2 as buy_price_per_m2_spot2,
                        maintenance_price as maintenance_price_mxn_spot2,
                        property_type as property_type_spot2,
                        total_area_clean as total_area_spot2,
                        amenities as amenities_spot2,
                        pictures as pictures_spot2,
                        url as url_spot2,
                        parking_spaces as parking_spaces_spot2,
                        condition as condition_spot2,
                        date_published as date_published_spot2
                        FROM blackprint_db_prd.presentation.dim_market_data_spot2
                        WHERE id_market_data_spot2 = ANY({fid}::int[])
                        ORDER BY date_published DESC '''
            

        except Exception as e:
            if connection:
                connection.rollback()
            resp =  Response.internal_server_error(message=str(e))
        finally:
            if cursor:
                cursor.close()
            if connection:
                self.db.disconnect()
            return resp

    def get_property_pois(self):
        pass

    def get_property_traffic(self):
        pass

    def get_property_demographic(self):
        pass