
class QueryController :

    def __init__(self):
        pass

    @staticmethod
    def get_property_query(filter):
        query = f'''
                Select  
                fid,
                ids_market_data_spot2,
                ids_market_data_inmuebles24,
                ids_market_data_propiedades,
                street_address, 
                centroid,
                is_on_market,
                total_surface_area,
                total_construction_area,
                year_built,
                special_facilities,
                unit_land_value,
                land_value,
                key_vus,
                predominant_level,
                total_houses,
                locality_size,
                floor_levels,
                h3_indexes,
                open_space,
                id_land_use,
                id_municipality,
                id_city_blocks,
                rent_price_spot2,
                rent_price_per_m2_spot2,
                buy_price_spot2,
                buy_price_per_m2_spot2,
                total_area_spot2,
                property_type_spot2,
                rent_price_inmuebles24,
                rent_price_per_m2_inmuebles24,
                buy_price_inmuebles24,
                buy_price_per_m2_inmuebles24,
                total_area_inmuebles24,
                property_type_inmuebles24,
                rent_price_propiedades,
                rent_price_per_m2_propiedades,
                buy_price_propiedades,
                buy_price_per_m2_propiedades,
                total_area_propiedades,
                block_type,
                density_d,
                usage_desc,
                city_link,
                scope,
                height,
                cos,
                cus,
                min_housing,
                ids_market_data_inmuebles24,
                crecimiento_promedio_municipal,
                crecimiento_promedio_entidad,
                crecimiento_promedio_ageb,
                brands_active_life_front,
                brands_arts_and_entertainment_front,
                brands_attractions_and_activities_front,
                brands_automotive_front,
                brands_eat_and_drink_front,
                brands_education_front,
                brands_financial_service_front,
                brands_health_and_medical_front,
                brands_public_service_and_government_front,
                brands_retail_front,
                brands_active_life_500m,
                brands_arts_and_entertainment_500m,
                brands_attractions_and_activities_500m,
                brands_automotive_500m,
                brands_eat_and_drink_500m,
                brands_education_500m,
                brands_financial_service_500m,
                brands_health_and_medical_500m,
                brands_public_service_and_government_500m,
                brands_retail_500m,
                brands_active_life_1km,
                brands_arts_and_entertainment_1km,
                brands_attractions_and_activities_1km,
                brands_automotive_1km,
                brands_eat_and_drink_1km,
                brands_education_1km,
                brands_financial_service_1km,
                brands_health_and_medical_1km,
                brands_public_service_and_government_1km,
                brands_retail_1km,
                at_rest_avg_x_hour_0_front,
                pedestrian_avg_x_hour_0_front,
                motor_vehicle_avg_x_hour_0_front,
                at_rest_avg_x_hour_1_front,
                pedestrian_avg_x_hour_1_front,
                motor_vehicle_avg_x_hour_1_front,
                at_rest_avg_x_hour_2_front,
                pedestrian_avg_x_hour_2_front,
                motor_vehicle_avg_x_hour_2_front,
                at_rest_avg_x_hour_3_front,
                pedestrian_avg_x_hour_3_front,
                motor_vehicle_avg_x_hour_3_front,
                at_rest_avg_x_hour_4_front,
                pedestrian_avg_x_hour_4_front,
                motor_vehicle_avg_x_hour_4_front,
                at_rest_avg_x_hour_5_front,
                pedestrian_avg_x_hour_5_front,
                motor_vehicle_avg_x_hour_5_front,
                at_rest_avg_x_hour_6_front,
                pedestrian_avg_x_hour_6_front,
                motor_vehicle_avg_x_hour_6_front,
                at_rest_avg_x_hour_7_front,
                pedestrian_avg_x_hour_7_front,
                motor_vehicle_avg_x_hour_7_front,
                at_rest_avg_x_hour_8_front,
                pedestrian_avg_x_hour_8_front,
                motor_vehicle_avg_x_hour_8_front,
                at_rest_avg_x_hour_9_front,
                pedestrian_avg_x_hour_9_front,
                motor_vehicle_avg_x_hour_9_front,
                at_rest_avg_x_hour_10_front,
                pedestrian_avg_x_hour_10_front,
                motor_vehicle_avg_x_hour_10_front,
                at_rest_avg_x_hour_11_front,
                pedestrian_avg_x_hour_11_front,
                motor_vehicle_avg_x_hour_11_front,
                at_rest_avg_x_hour_12_front,
                pedestrian_avg_x_hour_12_front,
                motor_vehicle_avg_x_hour_12_front,
                at_rest_avg_x_hour_13_front,
                pedestrian_avg_x_hour_13_front,
                motor_vehicle_avg_x_hour_13_front,
                at_rest_avg_x_hour_14_front,
                pedestrian_avg_x_hour_14_front,
                motor_vehicle_avg_x_hour_14_front,
                at_rest_avg_x_hour_15_front,
                pedestrian_avg_x_hour_15_front,
                motor_vehicle_avg_x_hour_15_front,
                at_rest_avg_x_hour_16_front,
                pedestrian_avg_x_hour_16_front,
                motor_vehicle_avg_x_hour_16_front,
                at_rest_avg_x_hour_17_front,
                pedestrian_avg_x_hour_17_front,
                motor_vehicle_avg_x_hour_17_front,
                at_rest_avg_x_hour_18_front,
                pedestrian_avg_x_hour_18_front,
                motor_vehicle_avg_x_hour_18_front,
                at_rest_avg_x_hour_19_front,
                pedestrian_avg_x_hour_19_front,
                motor_vehicle_avg_x_hour_19_front,
                at_rest_avg_x_hour_20_front,
                pedestrian_avg_x_hour_20_front,
                motor_vehicle_avg_x_hour_20_front,
                at_rest_avg_x_hour_21_front,
                pedestrian_avg_x_hour_21_front,
                motor_vehicle_avg_x_hour_21_front,
                at_rest_avg_x_hour_22_front,
                pedestrian_avg_x_hour_22_front,
                motor_vehicle_avg_x_hour_22_front,
                at_rest_avg_x_hour_23_front,
                pedestrian_avg_x_hour_23_front,
                motor_vehicle_avg_x_hour_23_front,
                at_rest_avg_x_day_of_week_1_front,
                pedestrian_avg_x_day_of_week_1_front,
                motor_vehicle_avg_x_day_of_week_1_front,
                at_rest_avg_x_day_of_week_2_front,
                pedestrian_avg_x_day_of_week_2_front,
                motor_vehicle_avg_x_day_of_week_2_front,
                at_rest_avg_x_day_of_week_3_front,
                pedestrian_avg_x_day_of_week_3_front,
                motor_vehicle_avg_x_day_of_week_3_front,
                at_rest_avg_x_day_of_week_4_front,
                pedestrian_avg_x_day_of_week_4_front,
                motor_vehicle_avg_x_day_of_week_4_front,
                at_rest_avg_x_day_of_week_5_front,
                pedestrian_avg_x_day_of_week_5_front,
                motor_vehicle_avg_x_day_of_week_5_front,
                at_rest_avg_x_day_of_week_6_front,
                pedestrian_avg_x_day_of_week_6_front,
                motor_vehicle_avg_x_day_of_week_6_front,
                at_rest_avg_x_day_of_week_7_front,
                pedestrian_avg_x_day_of_week_7_front,
                motor_vehicle_avg_x_day_of_week_7_front,
                at_rest_avg_x_day_of_week_1_500m,
                pedestrian_avg_x_day_of_week_1_500m,
                motor_vehicle_avg_x_day_of_week_1_500m,
                at_rest_avg_x_day_of_week_2_500m,
                pedestrian_avg_x_day_of_week_2_500m,
                motor_vehicle_avg_x_day_of_week_2_500m,
                at_rest_avg_x_day_of_week_3_500m,
                pedestrian_avg_x_day_of_week_3_500m,
                motor_vehicle_avg_x_day_of_week_3_500m,
                at_rest_avg_x_day_of_week_4_500m,
                pedestrian_avg_x_day_of_week_4_500m,
                motor_vehicle_avg_x_day_of_week_4_500m,
                at_rest_avg_x_day_of_week_5_500m,
                pedestrian_avg_x_day_of_week_5_500m,
                motor_vehicle_avg_x_day_of_week_5_500m,
                at_rest_avg_x_day_of_week_6_500m,
                pedestrian_avg_x_day_of_week_6_500m,
                motor_vehicle_avg_x_day_of_week_6_500m,
                at_rest_avg_x_day_of_week_7_500m,
                pedestrian_avg_x_day_of_week_7_500m,
                motor_vehicle_avg_x_day_of_week_7_500m,
                at_rest_avg_x_hour_0_500m,
                pedestrian_avg_x_hour_0_500m,
                motor_vehicle_avg_x_hour_0_500m,
                at_rest_avg_x_hour_1_500m,
                pedestrian_avg_x_hour_1_500m,
                motor_vehicle_avg_x_hour_1_500m,
                at_rest_avg_x_hour_2_500m,
                pedestrian_avg_x_hour_2_500m,
                motor_vehicle_avg_x_hour_2_500m,
                at_rest_avg_x_hour_3_500m,
                pedestrian_avg_x_hour_3_500m,
                motor_vehicle_avg_x_hour_3_500m,
                at_rest_avg_x_hour_4_500m,
                pedestrian_avg_x_hour_4_500m,
                motor_vehicle_avg_x_hour_4_500m,
                at_rest_avg_x_hour_5_500m,
                pedestrian_avg_x_hour_5_500m,
                motor_vehicle_avg_x_hour_5_500m,
                at_rest_avg_x_hour_6_500m,
                pedestrian_avg_x_hour_6_500m,
                motor_vehicle_avg_x_hour_6_500m,
                at_rest_avg_x_hour_7_500m,
                pedestrian_avg_x_hour_7_500m,
                motor_vehicle_avg_x_hour_7_500m,
                at_rest_avg_x_hour_8_500m,
                pedestrian_avg_x_hour_8_500m,
                motor_vehicle_avg_x_hour_8_500m,
                at_rest_avg_x_hour_9_500m,
                pedestrian_avg_x_hour_9_500m,
                motor_vehicle_avg_x_hour_9_500m,
                at_rest_avg_x_hour_10_500m,
                pedestrian_avg_x_hour_10_500m,
                motor_vehicle_avg_x_hour_10_500m,
                at_rest_avg_x_hour_11_500m,
                pedestrian_avg_x_hour_11_500m,
                motor_vehicle_avg_x_hour_11_500m,
                at_rest_avg_x_hour_12_500m,
                pedestrian_avg_x_hour_12_500m,
                motor_vehicle_avg_x_hour_12_500m,
                at_rest_avg_x_hour_13_500m,
                pedestrian_avg_x_hour_13_500m,
                motor_vehicle_avg_x_hour_13_500m,
                at_rest_avg_x_hour_14_500m,
                pedestrian_avg_x_hour_14_500m,
                motor_vehicle_avg_x_hour_14_500m,
                at_rest_avg_x_hour_15_500m,
                pedestrian_avg_x_hour_15_500m,
                motor_vehicle_avg_x_hour_15_500m,
                at_rest_avg_x_hour_16_500m,
                pedestrian_avg_x_hour_16_500m,
                motor_vehicle_avg_x_hour_16_500m,
                at_rest_avg_x_hour_17_500m,
                pedestrian_avg_x_hour_17_500m,
                motor_vehicle_avg_x_hour_17_500m,
                at_rest_avg_x_hour_18_500m,
                pedestrian_avg_x_hour_18_500m,
                motor_vehicle_avg_x_hour_18_500m,
                at_rest_avg_x_hour_19_500m,
                pedestrian_avg_x_hour_19_500m,
                motor_vehicle_avg_x_hour_19_500m,
                at_rest_avg_x_hour_20_500m,
                pedestrian_avg_x_hour_20_500m,
                motor_vehicle_avg_x_hour_20_500m,
                at_rest_avg_x_hour_21_500m,
                pedestrian_avg_x_hour_21_500m,
                motor_vehicle_avg_x_hour_21_500m,
                at_rest_avg_x_hour_22_500m,
                pedestrian_avg_x_hour_22_500m,
                motor_vehicle_avg_x_hour_22_500m,
                at_rest_avg_x_hour_23_500m,
                pedestrian_avg_x_hour_23_500m,
                motor_vehicle_avg_x_hour_23_500m
                FROM blackprint_db_prd.data_product.v_parcel_v3 ''' + filter
        return query
    
    @staticmethod
    def get_demographics_query(fid):
        query = f'''select 
                fid,
                neighborhood,
                nom_mun,
                predominant_level,
                ageb_code,
                vivtot, -- total houses
                vivtot_colonia,
                vivtot_alcaldia,
                prom_ocup, -- average household size
                prom_ocup_colonia, 
                prom_ocup_alcaldia,
                pro_ocup_c, -- average number of rooms
                pro_ocup_c_colonia, 
                pro_ocup_c_alcaldia, 
                ses_ab, -- socio-economic level AB
                ses_ab_colonia,
                ses_ab_alcaldia,
                ses_c_plus , -- socio-economic level C+
                ses_c_plus_colonia,
                ses_c_plus_alcaldia,
                ses_c, -- socio-economic level C
                ses_c_colonia,
                ses_c_alcaldia,
                ses_c_minus, -- socio-economic level C-
                ses_c_minus_colonia,
                ses_c_minus_alcaldia,
                ses_d , -- socio-economic level D
                ses_d_colonia,
                ses_d_alcaldia,
                ses_d_plus,  -- socio-economic level D+
                ses_d_plus_colonia,
                ses_d_plus_alcaldia,
                ses_e, -- socio-economic level E
                ses_e_colonia,
                ses_e_alcaldia,
                pobtot, -- total population
                pobtot_colonia,
                pobtot_alcaldia,
                pobmas, -- total male population
                pobmas_colonia,
                pobmas_alcaldia,
                pobfem, -- total female population
                pobfem_colonia,
                pobfem_alcaldia,
                p_3a5, -- total education between 3 and 5 years
                p_3a5_colonia,
                p_3a5_alcaldia,
                p3a5_noa, -- total education between 3 and 5 years attending school
                p3a5_noa_colonia,
                p3a5_noa_alcaldia,
                p_6a11, -- total education between 6 and 11 years
                p_6a11_colonia,
                p_6a11_alcaldia,
                p6a11_noa, -- total education between 6 and 11 years attending school
                p6a11_noa_colonia,
                p6a11_noa_alcaldia,
                p_12a14, -- total education between 12 and 14 years
                p_12a14_colonia,
                p_12a14_alcaldia,
                p12a14noa, -- total education between 12 and 14 years attending school
                p12a14noa_colonia,
                p12a14noa_alcaldia,
                p_15a17, -- total education between 15 and 17 years
                p_15a17_colonia,
                p_15a17_alcaldia,
                p15a17a, -- total education between 15 and 17 years attending school
                p15a17a_colonia,
                p15a17a_alcaldia,
                p_18a24 , -- total education between 18 and 24 years
                p_18a24_colonia,
                p_18a24_alcaldia,
                p18a24a, -- total education between 18 and 24 years attending school
                p18a24a_colonia,
                p18a24a_alcaldia,
                pea, -- total workforce
                pea_colonia,
                pea_alcaldia,
                pea_m,  -- total male workforce
                pea_m_colonia,
                pea_m_alcaldia,
                pea_f,  -- total female workforce
                pea_f_colonia,
                pea_f_alcaldia,
                pe_inac, -- total inactive population
                pe_inac_colonia,
                pe_inac_alcaldia,
                pe_inac_m, -- total inactive male population
                pe_inac_m_colonia,
                pe_inac_m_alcaldia,
                pe_inac_f, -- total inactive female population
                pe_inac_f_colonia,
                pe_inac_f_alcaldia,
                pocupada, -- total employed population
                pocupada_colonia, 
                pocupada_alcaldia,
                pocupada_m, -- total employed male population
                pocupada_m_colonia,
                pocupada_m_alcaldia,
                pocupada_f, -- total employed female population
                pocupada_f_colonia,
                pocupada_f_alcaldia,
                pdesocup, -- total unemployed population
                pdesocup_colonia,
                pdesocup_alcaldia,
                pdesocup_m, -- total unemployed male population
                pdesocup_m_colonia,
                pdesocup_m_alcaldia,
                pdesocup_f, -- total unemployed female population
                pdesocup_f_colonia,
                pdesocup_f_alcaldia
                from blackprint_db_prd.data_product.v_parcel_v3
                where fid = {fid}
                    '''
        return query
    
    @staticmethod
    def get_market_info_query(spot2, inmuebles24):
        if inmuebles24 :
            query = f'''
                    SELECT
                    "id_market_data_inmuebles24" AS "id_market_data_inmuebles24",
                    "title" AS "title",
                    "description" AS "description",
                    "rent_price" AS "rent_price",
                    "rent_price_clean" AS "rent_price_clean",
                    "rent_price_per_m2" AS "rent_price_per_m2",
                    "buy_price" AS "buy_price",
                    "buy_price_clean" AS "buy_price_clean",
                    "buy_price_per_m2" AS "buy_price_per_m2",
                    "maintenance_price" AS "maintenance_price",
                    "publication_date" AS "publication_date",
                    "parking_lot" AS "parking_lot",
                    "bathrooms" AS "bathrooms",
                    "bedrooms" AS "bedrooms",
                    "age" AS "age",
                    "pictures" AS "pictures",
                    "property_type" AS "property_type",
                    "operation_type" AS "operation_type",
                    "property_dimension" AS "total_area",
                    "property_dimension_clean" AS "total_area_clean",
                    "zone" AS "zone",
                    "city" AS "city",
                    "address" AS "address",
                    "url" AS "url",
                    "amenities" AS "amenities"
                    from blackprint_db_prd.presentation.dim_market_data_inmuebles24
                    where id_market_data_inmuebles24 = {inmuebles24} '''
        elif spot2:
            query = f""" SELECT
                        "id_market_data_spot2" AS "id_market_data_spot2",
                        "title" AS "title",
                        "address" AS "address",
                        "street_address" AS "street_address",
                        "city" AS "city",
                        "zip_code" AS "zip_code",
                        "description" AS "description",
                        "operation_type" AS "operation_type",
                        "rent_price" AS "rent_price",
                        "rent_price_clean" AS "rent_price_clean",
                        "rent_price_per_m2" AS "rent_price_per_m2",
                        "buy_price" AS "buy_price",
                        "buy_price_clean" AS "buy_price_clean",
                        "buy_price_per_m2" AS "buy_price_per_m2",
                        "maintenance_price" AS "maintenance_price",
                        "property_type" AS "property_type",
                        "total_area" AS "total_area",
                        "total_area_clean" AS "total_area_clean",
                        "amenities" AS "amenities",
                        "pictures" AS "pictures",
                        "url" AS "url",
                        "parking_spaces" AS "parking_spaces",
                        "condition" AS "condition",
                        "date_published" AS "publication_date"
                    FROM
                    blackprint_db_prd.presentation.dim_market_data_spot2
                    WHERE id_market_data_spot2 = {spot2} """        

        return query


