"""Added Group table

Revision ID: 2cb8a720dea7
Revises: 7c0fc3ea1d31
Create Date: 2025-02-25 00:43:06.253935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb8a720dea7'
down_revision = '7c0fc3ea1d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('grp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grp_name', sa.String(length=100), nullable=True),
    sa.Column('grp_status', sa.Integer(), nullable=True),
    sa.Column('property_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('grp_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    # ### end Alembic commands ###
