"""Initial migration for staging database

Revision ID: 7c0fc3ea1d31
Revises: 
Create Date: 2025-02-25 00:33:05.384549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c0fc3ea1d31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bp_prop_cache',
    sa.Column('bpc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bpc_fid', sa.Integer(), nullable=False),
    sa.Column('bpc_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bpc_created_at', sa.DateTime(), nullable=True),
    sa.Column('bpc_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bpc_id')
    )
    op.create_table('bp_saved_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('search_name', sa.String(length=100), nullable=True),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('search_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('search_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bp_users',
    sa.Column('bp_user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bp_name', sa.String(length=255), nullable=False),
    sa.Column('bp_company', sa.String(length=255), nullable=True),
    sa.Column('bp_industry', sa.String(length=255), nullable=True),
    sa.Column('bp_email', sa.String(length=255), nullable=False),
    sa.Column('bp_password', sa.String(length=255), nullable=False),
    sa.Column('bp_created_on', sa.DateTime(), nullable=True),
    sa.Column('bp_status', sa.Integer(), nullable=True),
    sa.Column('bp_is_onboarded', sa.Integer(), nullable=True),
    sa.Column('bp_user_verified', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bp_user_id')
    )
    op.create_table('bp_users_questionare',
    sa.Column('bp_user_questionare_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bp_user_id', sa.Integer(), nullable=True),
    sa.Column('bp_brand_name', sa.String(length=100), nullable=True),
    sa.Column('bp_category', sa.String(length=100), nullable=True),
    sa.Column('bp_product', sa.String(length=100), nullable=True),
    sa.Column('bp_market_segment', sa.String(length=100), nullable=True),
    sa.Column('bp_target_audience', sa.String(length=100), nullable=True),
    sa.Column('bp_competitor_brands', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('bp_complementary_brands', sa.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('bp_user_questionare_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bp_users_questionare')
    op.drop_table('bp_users')
    op.drop_table('bp_saved_searches')
    op.drop_table('bp_prop_cache')
    # ### end Alembic commands ###
